services:
  dev-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tutorial-nest
    networks:
      - belajar-nest

networks:
  belajar-nest:
